#!/usr/bin/env bash
#
# Configure/set plugin specific variables (used by all Make helper scripts)
# Copyright 2021 Eighty/20 Results by Wicked Strong Chicks, LLC (Thomas Sjolshagen <thomas@eighty20results.com>)
#

# Used in this script only
declare sed

# Plugin specific variables (declared global)
declare -x github_url
declare -x plugin_description_text
declare -x plugin_homepage
declare -x short_description
declare -x short_name
declare -x version
declare -x remote_server
declare -x wordpress_version

sed="$(which sed)"

if [[ -z "${sed}" ]]; then
    echo "Error: The sed utility is not installed. Exiting!"
    exit 1;
fi

short_description="E20R MailChimp Interest Groups for Paid Memberships Pro and WooCommerce"
plugin_description_text="Automatically add users to your MailChimp.com list(s) when they sign up/register/buy on your site. Includes support for MailChimp Groups and Interests, plus Merge Tags as defined on the MailChimp server(s)."
plugin_homepage="https://${remote_server}/paid-memberships-pro/do-it-for-me/"

short_name="$(${sed} -e 's/\.php//g' -e 's/class[\.-]//g' <<< "${1}")"
version="$(./bin/get_plugin_version.sh "${1}")"
remote_server="${2}"
github_url="https://github.com/eighty20results/${short_name}/"

# Plugin specific files to include/exclude and move if necessary during build
declare -x -a include=( \
    "${1}" \
    "class-activateutilitiesplugin.php" \
    "docs" \
    "js" \
    "languages" \
    "src" \
    "README.txt" \
    "README.md" \
    "CHANGELOG.md"
)
declare -x -a exclude=( \
    ".editorconfig" \
    ".env.testing" \
    ".gitignore" \
    ".phpcs.xml.dist"
    "*.yml" \
    "*.phar" \
    "*.json" \
    "composer.*" \
    "Makefile" \
    "*.neon" \
    "*.xml" \
    "vendor" \
    "tests" \
)
declare -x -a build=()

# Not a plugin specific variable, but expensive to populate
wordpress_version=$(wget -q -O - http://api.wordpress.org/core/stable-check/1.0/  | grep latest | awk '{ print $1 }' | sed -e 's/"//g')
